name: Tweet random BINI lyrics

on:
  push:
  #schedule:
  #- cron: '15,45 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest # Define the runner OS
    
    steps:      
      - uses: actions/checkout@v4 # Checkout the repository code
        name: Set up Python environment

      - name: Set Timezone
        uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: 'Asia/Singapore'
          timezoneMacos: 'Asia/Singapore'
          timezoneWindows: 'Singapore Standard Time'
        
      - uses: actions/setup-python@v5 # Setup Python environment
        with:
          python-version: '3.12' # Specify Python version 

      - name: Install dependencies 
        run: pip install -r requirements.txt # Install dependencies from requirements.txt
      
      - name: Run Python script (tweet random lyrics)
        run: python project.py 
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          LYRICS_TOKEN: ${{ secrets.LYRICS_TOKEN }}
          LYRICS_PATH: ${{ github.workspace }}/lyrics
        
